###########################################
#               ENDPOINTS                 #
###########################################
GET_USER_TOKEN: "/api/oauth/user/token"
AUTHORIZATIONS: "/api/oauth/authorizations"


###########################################
#        OAuth service parameters         #
###########################################
OAUTH:
  #URL: "https://oauth.itwarriors.ru"
  URL: "http://127.0.0.1:8000"
  API:
    LOGIN: "/api/oauth/login"
    AUTHORIZE: "/api/oauth/authorize"
    TOKEN: "/api/oauth/token"
    TOKEN_INFO: "/api/oauth/token_info"
    USER_INFO: "/api/oauth/user_info"


#############################################
#                LOGGING                    #
#############################################
ERROR_LOG_FILENAME: "auth_client.log"
